### ISSUE TITLE
can not find target 'deploy' in XXXX project.  Valid targets are: buiuld, serve, lint, test

### ISSUE THREAD

**Issue by tomschreck** [MansaGroup/nrwl-nx-action#1]
## Feature Request
Need ability to use custom targets with `MansaGroup/nrwl-nx-action@v1.0.1`.  

## Is your feature request related to a problem? Please describe.
I'm using [`@flowaccount/nx-serverless`](https://github.com/flowaccount/nx-plugins/tree/master/libs/nx-serverless) to facilitate deploying serverless projects in NX to AWS lambda.  `@flowaccount/nx-serverless` modifies NX project with additional targets like deploy, offline, and sls.   It seems `MansaGroup/nrwl-nx-action@v1.0.1` does not support targets other than build, serve, lint, and test.

I'm trying to chain together `@flowaccount/nx-serverless` with `MansaGroup/nrwl-nx-action@v1.0.1` to create a GitHUb workflow for deploying affected projects to AWS when a pull requests is closed.  However, I'm getting this error:

![image](https://user-images.githubusercontent.com/2521463/97790951-5da66980-1b9b-11eb-964c-ca89c3b55fb2.png)

Here is my GitHUb Workflow YML file:

```
name: pull-request

env:
  AWS_REGION_NAME: "us-east-2"

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:

    - name: checkout code
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        always-auth: true
        node-version: ${{ matrix.node-version }}

    - name: install Nrwl Nx
      run: npm i nx

    - name: Fetch other branches
      run: git fetch --no-tags --prune --depth=5 origin $GITHUB_BASE_REF

    - name: install dependencies
      run: npm ci

    - name: Nrwl Nx
      uses: MansaGroup/nrwl-nx-action@v1.0.1
      with:
        targets: build, deploy
        projects: occupations-api
        args: --base=origin/main --stage=dev --configuration=dev

```

## Describe the solution you'd like

I'd like to be able to utilize custom targets with `MansaGroup/nrwl-nx-action@v1.0.1`.  In addition to the targets from `@flowaccount/nx-serverless`, perhaps ability to run my own custom targets.  I can create custom targets with NX using `@nrwl/workspace:run-commands` builder.

## What is the motivation/use case for changing the behavior?

Adding this capability will aid in making flexible GitHub Actions workfflows.
