### ISSUE TITLE
"Error: Error: Failed to load the 'package.json' file, did you setup your project correctly?"

### ISSUE THREAD

**Issue by rgahan5c** [MansaGroup/nrwl-nx-action#15]
## Current behavior

Running action in GitHub, get error that can't load package.json.

## Expected behavior

Package.json is loaded

**Others:**
Action: 

```
on:
  pull_request:
    branches: [develop]

jobs:
  lint_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Directory change
        run: |
          cd <nx_directory>

      - name: Nrwl Nx
        uses: MansaGroup/nrwl-nx-action@v2.0.3
        with:
          targets: lint, build
```

Output:
> Run MansaGroup/nrwl-nx-action@v2.0.3
> 🔍 Ensuring Nx is available
> Error: Error: Failed to load the 'package.json' file, did you setup your project correctly?

I put a `pwd` and `ls` in the Directory Change step to ensure I was in the right place, the output included the proper `package.json` file.

**Comment by IamBlueSlime** [comment]
Hi!

First of all, thanks you for using the `nrwl-nx-action`.
When you are using a shell-based step (with `run:`), the shell is isolated from the rest of the workflow. This means that your step with the `cd` command does nothing as your script does nothing else than changing the directory. The following steps are not affected by the change.
Thankfully there is an option `working-directory:` that you can place on your step to change the execution directory of the step. This will enable you to run the action on your nx directory.

For instance:
```yaml
      - name: Nrwl Nx
        uses: MansaGroup/nrwl-nx-action@v2.0.3
        working-directory: <your nx directory>
        with:
          targets: lint, build
```

I'll let you try this solution before closing the issue :)
Thanks!

**Comment by rgahan5c** [comment]
This is no longer considered valid syntax, according to github actions editor

<img width="417" alt="image" src="https://user-images.githubusercontent.com/75390311/106036355-dd5cab00-609a-11eb-96a1-b488a29baf9c.png">

**Comment by IamBlueSlime** [comment]
Hi @rgahan5c!

Sorry for the long time, I've pushed a fix to your issue by introducing a new `workingDirectory` input on the `main` branch. Could you test by yourself by pointing to the branch directly in your workflow (with `uses: MansaGroup/nrwl-nx-action@main`)? Hope that it will be fixed.

Thanks!

**Comment by Geoffrey0** [comment]
I am getting the same issue. I want to run the nx commands in a subfolder of my repo. I am getting the following output when pointing to main:

Run mansagroup/nrwl-nx-action@main
  with:
    targets: lint,test,build
    workingDirectory: myFolderName
    all: false
    affected: true
    parallel: false
    maxParallel: 3
    nxCloud: false
/bin/docker exec  48cce44b0cda403faf1cec3b8215c903cfe5315d1fdd9a49a24b8c985ebd0d76 sh -c "cat /etc/*release | grep ^ID"
🔍 Ensuring Nx is available
Error: Error: Failed to load the 'package.json' file, did you setup your project correctly?

On an other project I am using this without the subfolder and it works perfectly.

**Comment by bbugh** [comment]
@IamBlueSlime the working directory for this library is `workingDirectory` in camel case, not kebab case.

I am having the same problem as @Geoffrey0. The output here does not appear:

https://github.com/MansaGroup/nrwl-nx-action/blob/d7451b35e0daab08a17d5573c5099322bb8e6e20/src/index.ts#L33-L36

though I'm not sure if the `info` output will be shown in the GitHub console.

**Comment by bbugh** [comment]
It works at the latest `HEAD` if you regenerate the `dist/index.js` file with `npm run package`. 

Looks like a new release build just needs to be made to fix this.

**Comment by IamBlueSlime** [comment]
> It works at the latest `HEAD` if you regenerate the `dist/index.js` file with `npm run package`.
> 
> Looks like a new release build just needs to be made to fix this.

I'll create a new release then! Thanks for pointing out!

**Comment by IamBlueSlime** [comment]
Done, [see here](https://github.com/MansaGroup/nrwl-nx-action/releases/tag/v2.0.4). Let me know if something is doing weird :)

**Comment by bbugh** [comment]
Works great now, thanks!

**Comment by IamBlueSlime** [comment]
Nice to hear!
I'm closing the issue, do not hesitate to open a new one if needed!

**Comment by jacewardell** [comment]
Hey, all! I'm running into this issue when using multiple jobs. I want to have build and test run separately so I can apply labels if one fails. To do that, I'm trying this:
```
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache `.npm` directory for faster future builds
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-npm--${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
          ${{ runner.os }}-

    - name: Run `npm ci` to get guaranteed dependency versions using package-lock
      run: npm ci
    
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Nx Test
      id: test
      uses: MansaGroup/nrwl-nx-action@v2
      with:
        targets: test
        workingDirectory: ./

    - name: Add 'Tests Failing' label if tests failed
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ failure() && contains(steps.test.conclusion, 'failure') }}
      with:
        github_token: ${{env.GITHUB_TOKEN}}
        labels: Tests Failing

    - name: Remove 'Tests Failing' label if present and tests passed
      uses: actions-ecosystem/action-remove-labels@v1
      if: ${{ success() && contains(toJson(github.event.pull_request.labels), 'Tests Failing') }}
      with:
        github_token: ${{env.GITHUB_TOKEN}}
        labels: Tests Failing
        
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Nx Build
      id: build
      uses: MansaGroup/nrwl-nx-action@v2
      with:
        targets: build
        workingDirectory: ./

    - name: Add 'Build Failing' label if build failed
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ failure() && contains(steps.build.conclusion, 'failure') }}
      with:
        github_token: ${{env.GITHUB_TOKEN}}
        labels: Build Failing

    - name: Remove 'Build Failing' label if present and build succeeded
      uses: actions-ecosystem/action-remove-labels@v1
      if: ${{ success() && contains(toJson(github.event.pull_request.labels), 'Build Failing') }}
      with:
        github_token: ${{env.GITHUB_TOKEN}}
        labels: Build Failing 
```
As you can see, I attempted to use `workingDirectory` like was mentioned above, but that didn't help. My Nx project is at the root of the repo and doesn't seem like that option's required. Do you guys have any suggestions?
