### ISSUE TITLE
How to target base=master ? Issue with Command failed: git merge-base --fork-point

### ISSUE THREAD

**Issue by gamegee** [MansaGroup/nrwl-nx-action#306]
## Feature Request
My current flow for running the CI is the following :
- Create a feature branch
- Push the feature branch
- Create a pull request with the base branch `master`

I am wondering how I can run `affected` running a comparison between the last commit of master `--base=master` and the last commit of the current branch.

Here is an example of my `.github-action` configuration:
```yml
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install-deps # other job installing the deps => npm i
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - uses: mansagroup/nrwl-nx-action@v2
        with:
          args: --verbose=false
          targets: test
```

## Is your feature request related to a problem? Please describe.
When running the CI I have the following error :
```sh
nx "affected" "--target=test" "--base=bb2066fa076f1afc2cf0ced20096b56f2ad51c80" "--head=78f6e6aabdc9541d462fdba1ce770342068f2db2" "--verbose=false"

fatal: Not a valid commit name bb2066fa076f1afc2cf0ced20096b56f2ad51c80
fatal: No such ref: 'bb2066fa076f1afc2cf0ced20096b56f2ad51c80'

...

Error: Command failed: git merge-base --fork-point "bb2066fa076f1afc2cf0ced20096b56f2ad51c80" "78f6e6aabdc9541d462fdba1ce770342068f2db2"
fatal: No such ref: 'bb2066fa076f1afc2cf0ced20096b56f2ad51c80'
```

## Describe the solution you'd like
I am not sure if I should be able to fix my issue, I want to be able to define my base being `master`.
Did I miss something or `nrwl-nx-action` should provide an API to resolve my issue ?

## Teachability, Documentation, Adoption, Migration Strategy
-
