### ISSUE TITLE
The process '/opt/hostedtoolcache/node/16.17.1/x64/bin/npm' failed with exit code 127

### ISSUE THREAD

**Issue by mrcreatist** [MansaGroup/nrwl-nx-action#307]
## Current behavior

Whenever I am running the CI/CD, getting the following error:
```
Run mansagroup/nrwl-nx-action@v2
🏃 Working in custom directory: ./
🔍 Ensuring Nx is available
/opt/hostedtoolcache/node/16.17.1/x64/bin/npm run nx -- run-many --target=lint --all
 app@0.0.0 nx
 nx
/tmp/nx-d1766103.sh: 1: nx: not found
Error: Error: The process '/opt/hostedtoolcache/node/16.17.1/x64/bin/npm' failed with exit code 127
```

Code:
```
name: Nx CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - uses: mansagroup/nrwl-nx-action@v2
      with:
        targets: lint,build
        all: 'true'
        workingDirectory: ./
```

This error is occurring every time.
