### ISSUE TITLE
Failed to locate the 'nx' script in package.json, did you setup your project with Nx's CLI?

### ISSUE THREAD

**Issue by Megajin** [MansaGroup/nrwl-nx-action#323]
## Bug Report
Hi everyone, I am trying to figure out why my workflow keeps crashing. When entering the NX step the following will be shown in the GitHub Actions console:

```
Run mansagroup/nrwl-nx-action@v2
🔍 Ensuring Nx is available
Error: Error: Failed to locate the 'nx' script in package.json, did you setup your project with Nx's CLI?
```

I have tried `yarn` as well as `npm` both with the same results. However in our project we are only using `yarn` as our package manager. Here ist the workflow.yaml:

```yaml
name: Tests, Docs, Changelogs, Publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build_lint_test_docs_readme_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"
          registry-url: https://registry.npmjs.org/
          cache: "yarn"
      - name: Install Repo deps
        run: yarn install
      - name: Configure CI Git User
        run: |
          git config --global user.email ci-bot@github.com
          git config --global user.name GitHub Actions
      - name: Run NX Tasks
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: version
          projects: array-utils
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DREAM_BIT_UTILS_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 📝 Automated Docs and Readmes

```

## Current behavior

Error will show up while checking in the task `mansagroup/nrwl-nx-action@v2`.

## Expected behavior
It should run the wanted NX task for the choosen project.

## Possible Solution
I don't know at the moment.

---

**Others:**
